name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add SHORT_SHA env property with commit short sha
        run: |
          echo "SHORT_SHA=\"\$(git rev-parse --short HEAD)\"" >> $GITHUB_ENV
          echo "IMAGE_TAG=\"sardylan/aprs2influxdb:${SHORT_SHA}\"" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        run: docker login -u sardylan -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Run tests
        run: docker image build --target=test .
      - name: Build the Docker image
        run: docker image build --target=prod --tag ${IMAGE_TAG} .
      - name: Publich the Docker image
        run: docker image push ${IMAGE_TAG}
